# Custom hors langue

[ejs.app]
title = "PSU & DD collab Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/PlaySorbonne/PSU-Launcher/"
mediaTwitterURL = "https://twitter.com/PlaySorbonneU"
mediaInstagramURL = "https://www.instagram.com/play_sorbonne_u/"
mediaYouTubeURL = "https://www.youtube.com/@PlaySorbonne"
mediaDiscordURL = "https://discord.gg/HWhRdvxraJ"

[ejs.settings]
sourceGithubLink = "https://github.com/PlaySorbonne/PSU-Launcher/"
supportLink = "https://github.com/PlaySorbonne/PSU-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le lanceur du serveur PSU et Dideros et Dragons"
welcomeDescription = ":3 :3 :3"
welcomeDescCTA = "Tu n'es qu'à quelques clics du serveur PSU !"
